# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointledgerentry",
            name="reason",
            field=models.CharField(max_length=120),
        ),
    ]
